export const weatherDescriptions = {
    'clear sky': { description: 'céu limpo', color: '#79b7ee' },
    'few clouds': { description: 'poucas nuvens', color: '#969494' },
    'scattered clouds': { description: 'nuvens dispersas', color: '#c1c0c0' },
    'broken clouds': { description: 'nuvens quebradas', color: '#ADD8E6' },
    'overcast clouds': { description: 'nuvens nubladas', color: '#785478' },
    'light rain': { description: 'chuva leve', color: '#00BFFF' },
    'moderate rain': { description: 'chuva moderada', color: '#0000FF' },
    'heavy rain': { description: 'chuva intensa', color: '#000080' },
    'light snow': { description: 'neve leve', color: '#f9f9f9' },
    'moderate snow': { description: 'neve moderada', color: '#EEE8AA' },
    'heavy snow': { description: 'neve intensa', color: '#FFFAFA' },
    'mist': { description: 'névoa', color: '#8B4513' },
    'fog': { description: 'nevoeiro', color: '#8B4513' },
    'thunderstorm': { description: 'tempestade', color: '#0f0c37' },
    'drizzle': { description: 'chuvisco', color: '#87CEEB' },
    'smoke': { description: 'fumaça', color: '#A9A9A9' },
};
